// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeEkwZCQQMH6aMzQsQ9NPFxaETQZPeA2E',
    appId: '1:357972785166:web:1e719ac05b1c62826f645f',
    messagingSenderId: '357972785166',
    projectId: 'final-bbdd4',
    authDomain: 'final-bbdd4.firebaseapp.com',
    storageBucket: 'final-bbdd4.appspot.com',
    measurementId: 'G-HL1TH3MGP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJuhP7_xJgow8ihycH6VoGTqJe3eg33o',
    appId: '1:357972785166:android:d8392196dee2b8af6f645f',
    messagingSenderId: '357972785166',
    projectId: 'final-bbdd4',
    storageBucket: 'final-bbdd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAeAHP1aBXwrEd3Ke9TWKKlIqdkr8BS4',
    appId: '1:357972785166:ios:9b02e14ab8d094636f645f',
    messagingSenderId: '357972785166',
    projectId: 'final-bbdd4',
    storageBucket: 'final-bbdd4.appspot.com',
    iosBundleId: 'com.example.ohmsLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEAeAHP1aBXwrEd3Ke9TWKKlIqdkr8BS4',
    appId: '1:357972785166:ios:9b02e14ab8d094636f645f',
    messagingSenderId: '357972785166',
    projectId: 'final-bbdd4',
    storageBucket: 'final-bbdd4.appspot.com',
    iosBundleId: 'com.example.ohmsLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeEkwZCQQMH6aMzQsQ9NPFxaETQZPeA2E',
    appId: '1:357972785166:web:4ff04881e5b23fae6f645f',
    messagingSenderId: '357972785166',
    projectId: 'final-bbdd4',
    authDomain: 'final-bbdd4.firebaseapp.com',
    storageBucket: 'final-bbdd4.appspot.com',
    measurementId: 'G-4B289820M9',
  );

}