// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJXb0dOt5_5xCKYkGXIfhbJNwUko8CYl8',
    appId: '1:723400451890:web:f28d77f6b81ad41327592b',
    messagingSenderId: '723400451890',
    projectId: 'ohms-b49d6',
    authDomain: 'ohms-b49d6.firebaseapp.com',
    storageBucket: 'ohms-b49d6.appspot.com',
    measurementId: 'G-VLPD243SWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9r1TNeLOR8qO3NAg2CVVbQACW5aBgxc8',
    appId: '1:723400451890:android:a30eeec616a7814f27592b',
    messagingSenderId: '723400451890',
    projectId: 'ohms-b49d6',
    storageBucket: 'ohms-b49d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOxhRJRfqfKYryelCRLfIZFn73ShSpqLw',
    appId: '1:723400451890:ios:07b872459ab1448c27592b',
    messagingSenderId: '723400451890',
    projectId: 'ohms-b49d6',
    storageBucket: 'ohms-b49d6.appspot.com',
    iosBundleId: 'com.example.ohmsLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOxhRJRfqfKYryelCRLfIZFn73ShSpqLw',
    appId: '1:723400451890:ios:07b872459ab1448c27592b',
    messagingSenderId: '723400451890',
    projectId: 'ohms-b49d6',
    storageBucket: 'ohms-b49d6.appspot.com',
    iosBundleId: 'com.example.ohmsLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJXb0dOt5_5xCKYkGXIfhbJNwUko8CYl8',
    appId: '1:723400451890:web:e150761b74b2d6ed27592b',
    messagingSenderId: '723400451890',
    projectId: 'ohms-b49d6',
    authDomain: 'ohms-b49d6.firebaseapp.com',
    storageBucket: 'ohms-b49d6.appspot.com',
    measurementId: 'G-799MVL33KC',
  );
}
