import 'package:flutter/material.dart';
import 'package:ohms_login/LoginPage.dart';
import 'package:ohms_login/ResetPasswordPage.dart';
import 'package:ohms_login/SignUpPage.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is the file generated by FlutterFire CLI


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Use generated options
  );
  runApp( const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Auth App',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const LoginPage(),
      routes: {
        '/signup': (context) => const SignUpPage(),
        '/reset-password': (context) =>  const ResetPasswordPage(),
      },
    );
  }
}

